version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: admin
       MONGO_INITDB_DATABASE: Chats
    volumes:
      - mongo_db:/data/db
    networks:
      - mongo
    ports:
      - 27017:27017
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--username", "root", "--password", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s

  chatboat:
    build:
      context: .
      dockerfile: ./Docker-multi-stage
    container_name: chatMongo
    environment:
      DB_HOST: mongodb-container
      DB_USER: root
      DB_PASSWORD: admin
      DB_DATABASE: Chats
    networks:
      - mongo
    ports:
      - 7080:7080
    depends_on:
      - mongodb
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:7080/"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s


volumes:
  mongo_db:

networks:
  mongo:

